apiVersion: k8s.kiwi.com/v1
kind: VaultSecret
metadata:
  name: benchmark-$COUNT
  namespace: example
spec:
  addr: http://127.0.0.1:8200
  path: secret/gcp-project/dutchman-sandbox-688fdbc1/general-secrets
  targetSecretName: benchmark-secret-from-vault-$COUNT
  reconcilePeriod: 1m
  auth:
    tokenSecretRef:
      name: benchmark-vault-token
      key: VAULT_TOKEN
