version: '3'

services:
  vault:
    image: vault:1.12.2
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    command: server -dev --log-level=trace -dev-listen-address=0.0.0.0:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken

  runner:
    image: golang:alpine
    cap_add:
      - IPC_LOCK
    environment:
      GOPROXY: https://goproxy.io
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: testtoken
    volumes:
    - .:/app

