apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: vault-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-vault-operator
    app.kubernetes.io/part-of: k8s-vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: vault-operator
  namespace: system
