# permissions for end users to edit vaultsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vaultsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-vault-operator
    app.kubernetes.io/part-of: k8s-vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: vaultsecret-editor-role
rules:
- apiGroups:
  - k8s.kiwi.com
  resources:
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kiwi.com
  resources:
  - vaultsecrets/status
  verbs:
  - get
